"""Changed Subtask.hours to Integer

Revision ID: 7b6198ae284f
Revises: 3655249a520a
Create Date: 2025-02-28 18:29:55.599043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b6198ae284f'
down_revision = '3655249a520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtasks', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
