"""Rebuilding migrations

Revision ID: 901b11ae15e8
Revises: 
Create Date: 2025-03-03 11:33:13.697605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '901b11ae15e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('deadline')
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.ENUM('pending', 'approved', 'rejected', 'in_review'), nullable=True))

    # ### end Alembic commands ###
